#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Plot results from extension of Vannitsem & Liang (2022) - Liang index with lag
With variables downloaded by DD on 20/01/2023
With 12 lags (11 months)

Last updated: 28/06/2023

@author: David Docquier
"""

# Import libraries
import numpy as np
import matplotlib.pyplot as plt

# Options
save_fig = True
nvar = int(8*12)
nlag = 11
lag = np.linspace(0,nlag,12)
conf = 1.96

# Load results LKIF
filename = 'real_case_study_liang_lags.npy'
notused,tau,notused,notused,error_tau,notused,notused,sig_tau,notused = np.load(filename,allow_pickle=True)
tau = np.abs(tau)
tau[sig_tau==0] = 0

# Scatter plots LKIF
fig = plt.figure(figsize=(24,30))
fig.subplots_adjust(left=0.08,bottom=0.05,right=0.95,top=0.95,wspace=0.2,hspace=0.31)

# Scatter plot of tau as a function of lag - PNA
ax = fig.add_subplot(4,2,1)
#ax.plot(lag,tau[0::8,1],'b--',label='$PNA_{t-l} \longrightarrow NAO_t$')
#ax.plot(lag,tau[0::8,2],'r--',label='$PNA_{t-l} \longrightarrow AO_t$')
#ax.plot(lag,tau[0::8,3],'k--',label='$PNA_{t-l} \longrightarrow QBO_t$')
ax.plot(lag,tau[0::8,4],'--',color='gray',label='$PNA_{t-l} \longrightarrow AMO_t$')
ax.plot(lag,tau[0::8,5],'b-',label='$PNA_{t-l} \longrightarrow PDO_t$')
#ax.plot(lag,tau[0::8,6],'r-',label='$PNA_{t-l} \longrightarrow TNA_t$')
ax.plot(lag,tau[0::8,7],'k-',label='$PNA_{t-l} \longrightarrow ENSO_t$')
ax.plot(lag[sig_tau[0::8,1]==1],tau[0::8,1][sig_tau[0::8,1]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[0::8,2]==1],tau[0::8,2][sig_tau[0::8,2]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[0::8,3]==1],tau[0::8,3][sig_tau[0::8,3]==1],'ko',markersize=15)
ax.plot(lag[sig_tau[0::8,4]==1],tau[0::8,4][sig_tau[0::8,4]==1],'o',color='gray',markersize=15)
ax.plot(lag[sig_tau[0::8,5]==1],tau[0::8,5][sig_tau[0::8,5]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[0::8,6]==1],tau[0::8,6][sig_tau[0::8,6]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[0::8,7]==1],tau[0::8,7][sig_tau[0::8,7]==1],'ko',markersize=15)
ax.legend(loc='upper right',fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Rate of information transfer $|\tau|$ ($\%$)',fontsize=24)
ax.grid(linestyle='--')
ax.set_ylim([-0.5,15])
ax.set_title('PNA influence',fontsize=28)
ax.set_title('(a)',loc='left',fontsize=28,fontweight='bold')
    
# Scatter plot of tau as a function of lag - NAO
ax = fig.add_subplot(4,2,2)
#ax.plot(lag,tau[1::8,0],'b--',label='$NAO_{t-l} \longrightarrow PNA_t$')
#ax.plot(lag,tau[1::8,2],'r--',label='$NAO_{t-l} \longrightarrow AO_t$')
#ax.plot(lag,tau[1::8,3],'k--',label='$NAO_{t-l} \longrightarrow QBO_t$')
#ax.plot(lag,tau[1::8,4],'--',color='gray',label='$NAO_{t-l} \longrightarrow AMO$')
ax.plot(lag,tau[1::8,5],'b-',label='$NAO_{t-l} \longrightarrow PDO$')
ax.plot(lag,tau[1::8,6],'r-',label='$NAO_{t-l} \longrightarrow TNA$')
#ax.plot(lag,tau[1::8,7],'k-',label='$NAO_{t-l} \longrightarrow ENSO$')
ax.plot(lag[sig_tau[1::8,0]==1],tau[1::8,0][sig_tau[1::8,0]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[1::8,2]==1],tau[1::8,2][sig_tau[1::8,2]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[1::8,3]==1],tau[1::8,3][sig_tau[1::8,3]==1],'ko',markersize=15)
ax.plot(lag[sig_tau[1::8,4]==1],tau[1::8,4][sig_tau[1::8,4]==1],'o',color='gray',markersize=15)
ax.plot(lag[sig_tau[1::8,5]==1],tau[1::8,5][sig_tau[1::8,5]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[1::8,6]==1],tau[1::8,6][sig_tau[1::8,6]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[1::8,7]==1],tau[1::8,7][sig_tau[1::8,7]==1],'ko',markersize=15)
ax.legend(loc='upper right',fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Rate of information transfer $|\tau|$ ($\%$)',fontsize=24)
ax.grid(linestyle='--')
ax.set_ylim([-0.5,15])
ax.set_title('NAO influence',fontsize=28)
ax.set_title('(b)',loc='left',fontsize=28,fontweight='bold')

# Scatter plot of tau as a function of lag - AO
ax = fig.add_subplot(4,2,3)
ax.plot(lag,tau[2::8,0],'b--',label='$AO_{t-l} \longrightarrow PNA$')
ax.plot(lag,tau[2::8,1],'r--',label='$AO_{t-l} \longrightarrow NAO$')
#ax.plot(lag,tau[2::8,3],'k--',label='$AO_{t-l} \longrightarrow QBO$')
ax.plot(lag,tau[2::8,4],'--',color='gray',label='$AO_{t-l} \longrightarrow AMO$')
ax.plot(lag,tau[2::8,5],'b-',label='$AO_{t-l} \longrightarrow PDO$')
ax.plot(lag,tau[2::8,6],'r-',label='$AO_{t-l} \longrightarrow TNA$')
#ax.plot(lag,tau[2::8,7],'k-',label='$AO_{t-l} \longrightarrow ENSO$')
ax.plot(lag[sig_tau[2::8,0]==1],tau[2::8,0][sig_tau[2::8,0]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[2::8,1]==1],tau[2::8,1][sig_tau[2::8,1]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[2::8,3]==1],tau[2::8,3][sig_tau[2::8,3]==1],'ko',markersize=15)
ax.plot(lag[sig_tau[2::8,4]==1],tau[2::8,4][sig_tau[2::8,4]==1],'o',color='gray',markersize=15)
ax.plot(lag[sig_tau[2::8,5]==1],tau[2::8,5][sig_tau[2::8,5]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[2::8,6]==1],tau[2::8,6][sig_tau[2::8,6]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[2::8,7]==1],tau[2::8,7][sig_tau[2::8,7]==1],'ko',markersize=15)
ax.legend(loc='upper right',fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Rate of information transfer $|\tau|$ ($\%$)',fontsize=24)
ax.grid(linestyle='--')
ax.set_ylim([-0.5,15])
ax.set_title('AO influence',fontsize=28)
ax.set_title('(c)',loc='left',fontsize=28,fontweight='bold')
    
# Scatter plot of tau as a function of lag - QBO
ax = fig.add_subplot(4,2,4)
#ax.plot(lag,tau[3::8,0],'b--',label='$QBO_{t-l} \longrightarrow PNA$')
#ax.plot(lag,tau[3::8,1],'r--',label='$QBO_{t-l} \longrightarrow NAO$')
#ax.plot(lag,tau[3::8,2],'k--',label='$QBO_{t-l} \longrightarrow AO$')
#ax.plot(lag,tau[3::8,4],'--',color='gray',label='$QBO_{t-l} \longrightarrow AMO$')
#ax.plot(lag,tau[3::8,5],'b-',label='$QBO_{t-l} \longrightarrow PDO$')
#ax.plot(lag,tau[3::8,6],'r-',label='$QBO_{t-l} \longrightarrow TNA$')
#ax.plot(lag,tau[3::8,7],'k-',label='$QBO_{t-l} \longrightarrow ENSO$')
ax.plot(lag[sig_tau[3::8,0]==1],tau[3::8,0][sig_tau[3::8,0]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[3::8,1]==1],tau[3::8,1][sig_tau[3::8,1]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[3::8,2]==1],tau[3::8,2][sig_tau[3::8,2]==1],'ko',markersize=15)
ax.plot(lag[sig_tau[3::8,4]==1],tau[3::8,4][sig_tau[3::8,4]==1],'o',color='gray',markersize=15)
ax.plot(lag[sig_tau[3::8,5]==1],tau[3::8,5][sig_tau[3::8,5]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[3::8,6]==1],tau[3::8,6][sig_tau[3::8,6]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[3::8,7]==1],tau[3::8,7][sig_tau[3::8,7]==1],'ko',markersize=15)
ax.legend(loc='upper right',fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Rate of information transfer $|\tau|$ ($\%$)',fontsize=24)
ax.grid(linestyle='--')
ax.axis([-0.5,11.5,-0.5,15])
ax.set_title('QBO influence',fontsize=28)
ax.set_title('(d)',loc='left',fontsize=28,fontweight='bold')
    
# Scatter plot of tau as a function of lag - AMO
ax = fig.add_subplot(4,2,5)
#ax.plot(lag,tau[4::8,0],'b--',label='$AMO_{t-l} \longrightarrow PNA$')
ax.plot(lag,tau[4::8,1],'r--',label='$AMO_{t-l} \longrightarrow NAO$')
#ax.plot(lag,tau[4::8,2],'k--',label='$AMO_{t-l} \longrightarrow AO$')
#ax.plot(lag,tau[4::8,3],'--',color='gray',label='$AMO_{t-l} \longrightarrow QBO$')
#ax.plot(lag,tau[4::8,5],'b-',label='$AMO_{t-l} \longrightarrow PDO$')
ax.plot(lag,tau[4::8,6],'r-',label='$AMO_{t-l} \longrightarrow TNA$')
#ax.plot(lag,tau[4::8,7],'k-',label='$AMO_{t-l} \longrightarrow ENSO$')
ax.plot(lag[sig_tau[4::8,0]==1],tau[4::8,0][sig_tau[4::8,0]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[4::8,1]==1],tau[4::8,1][sig_tau[4::8,1]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[4::8,2]==1],tau[4::8,2][sig_tau[4::8,2]==1],'ko',markersize=15)
ax.plot(lag[sig_tau[4::8,3]==1],tau[4::8,3][sig_tau[4::8,3]==1],'o',color='gray',markersize=15)
ax.plot(lag[sig_tau[4::8,5]==1],tau[4::8,5][sig_tau[4::8,5]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[4::8,6]==1],tau[4::8,6][sig_tau[4::8,6]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[4::8,7]==1],tau[4::8,7][sig_tau[4::8,7]==1],'ko',markersize=15)
ax.legend(loc='upper right',fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Rate of information transfer $|\tau|$ ($\%$)',fontsize=24)
ax.grid(linestyle='--')
ax.set_ylim([-0.5,15])
ax.set_title('AMO influence',fontsize=28)
ax.set_title('(e)',loc='left',fontsize=28,fontweight='bold')

# Scatter plot of tau as a function of lag - PDO
ax = fig.add_subplot(4,2,6)
ax.plot(lag,tau[5::8,0],'b--',label='$PDO_{t-l} \longrightarrow PNA$')
#ax.plot(lag,tau[5::8,1],'r--',label='$PDO_{t-l} \longrightarrow NAO$')
#ax.plot(lag,tau[5::8,2],'k--',label='$PDO_{t-l} \longrightarrow AO$')
#ax.plot(lag,tau[5::8,3],'--',color='gray',label='$PDO_{t-l} \longrightarrow QBO$')
ax.plot(lag,tau[5::8,4],'b-',label='$PDO_{t-l} \longrightarrow AMO$')
#ax.plot(lag,tau[5::8,6],'r-',label='$PDO_{t-l} \longrightarrow TNA$')
#ax.plot(lag,tau[5::8,7],'k-',label='$PDO_{t-l} \longrightarrow ENSO$')
ax.plot(lag[sig_tau[5::8,0]==1],tau[5::8,0][sig_tau[5::8,0]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[5::8,1]==1],tau[5::8,1][sig_tau[5::8,1]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[5::8,2]==1],tau[5::8,2][sig_tau[5::8,2]==1],'ko',markersize=15)
ax.plot(lag[sig_tau[5::8,3]==1],tau[5::8,3][sig_tau[5::8,3]==1],'o',color='gray',markersize=15)
ax.plot(lag[sig_tau[5::8,4]==1],tau[5::8,4][sig_tau[5::8,4]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[5::8,6]==1],tau[5::8,6][sig_tau[5::8,6]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[5::8,7]==1],tau[5::8,7][sig_tau[5::8,7]==1],'ko',markersize=15)
ax.legend(loc='upper right',fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Rate of information transfer $|\tau|$ ($\%$)',fontsize=24)
ax.grid(linestyle='--')
ax.set_ylim([-0.5,15])
ax.set_title('PDO influence',fontsize=28)
ax.set_title('(f)',loc='left',fontsize=28,fontweight='bold')

# Scatter plot of tau as a function of lag - TNA
ax = fig.add_subplot(4,2,7)
#ax.plot(lag,tau[6::8,0],'b--',label='$TNA_{t-l} \longrightarrow PNA$')
#ax.plot(lag,tau[6::8,1],'r--',label='$TNA_{t-l} \longrightarrow NAO$')
#ax.plot(lag,tau[6::8,2],'k--',label='$TNA_{t-l} \longrightarrow AO$')
#ax.plot(lag,tau[6::8,3],'--',color='gray',label='$TNA_{t-l} \longrightarrow QBO$')
ax.plot(lag,tau[6::8,4],'b-',label='$TNA_{t-l} \longrightarrow AMO$')
ax.plot(lag,tau[6::8,5],'r-',label='$TNA_{t-l} \longrightarrow PDO$')
ax.plot(lag,tau[6::8,7],'k-',label='$TNA_{t-l} \longrightarrow ENSO$')
ax.plot(lag[sig_tau[6::8,0]==1],tau[6::8,0][sig_tau[6::8,0]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[6::8,1]==1],tau[6::8,1][sig_tau[6::8,1]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[6::8,2]==1],tau[6::8,2][sig_tau[6::8,2]==1],'ko',markersize=15)
ax.plot(lag[sig_tau[6::8,3]==1],tau[6::8,3][sig_tau[6::8,3]==1],'o',color='gray',markersize=15)
ax.plot(lag[sig_tau[6::8,4]==1],tau[6::8,4][sig_tau[6::8,4]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[6::8,5]==1],tau[6::8,5][sig_tau[6::8,5]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[6::8,7]==1],tau[6::8,7][sig_tau[6::8,7]==1],'ko',markersize=15)
ax.legend(loc='upper right',fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Rate of information transfer $|\tau|$ ($\%$)',fontsize=24)
ax.grid(linestyle='--')
ax.set_ylim([-0.5,15])
ax.set_title('TNA influence',fontsize=28)
ax.set_title('(g)',loc='left',fontsize=28,fontweight='bold')

# Scatter plot of tau as a function of lag - ENSO
ax = fig.add_subplot(4,2,8)
#ax.plot(lag,tau[7::8,0],'b--',label='$ENSO_{t-l} \longrightarrow PNA$')
#ax.plot(lag,tau[7::8,1],'r--',label='$ENSO_{t-l} \longrightarrow NAO$')
#ax.plot(lag,tau[7::8,2],'k--',label='$ENSO_{t-l} \longrightarrow AO$')
#ax.plot(lag,tau[7::8,3],'--',color='gray',label='$ENSO_{t-l} \longrightarrow QBO$')
#ax.plot(lag,tau[7::8,4],'b-',label='$ENSO_{t-l} \longrightarrow AMO$')
ax.plot(lag,tau[7::8,5],'r-',label='$ENSO_{t-l} \longrightarrow PDO$')
ax.plot(lag,tau[7::8,6],'k-',label='$ENSO_{t-l} \longrightarrow TNA$')
ax.plot(lag[sig_tau[7::8,0]==1],tau[7::8,0][sig_tau[7::8,0]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[7::8,1]==1],tau[7::8,1][sig_tau[7::8,1]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[7::8,2]==1],tau[7::8,2][sig_tau[7::8,2]==1],'ko',markersize=15)
ax.plot(lag[sig_tau[7::8,3]==1],tau[7::8,3][sig_tau[7::8,3]==1],'o',color='gray',markersize=15)
ax.plot(lag[sig_tau[7::8,4]==1],tau[7::8,4][sig_tau[7::8,4]==1],'bo',markersize=15)
ax.plot(lag[sig_tau[7::8,5]==1],tau[7::8,5][sig_tau[7::8,5]==1],'ro',markersize=15)
ax.plot(lag[sig_tau[7::8,6]==1],tau[7::8,6][sig_tau[7::8,6]==1],'ko',markersize=15)
ax.legend(loc='upper right',fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Rate of information transfer $|\tau|$ ($\%$)',fontsize=24)
ax.grid(linestyle='--')
ax.set_ylim([-0.5,15])
ax.set_title('ENSO influence',fontsize=28)
ax.set_title('(h)',loc='left',fontsize=28,fontweight='bold')

# Save figure
if save_fig == True:
    fig.savefig('/home/dadocq/Documents/Papers/My_Papers/Causal_Comp/LaTeX/fig9.png')