#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Plot results from extension of Vannitsem & Liang (2022) - PCMCI
With variables downloaded by DD on 20/01/2023
With 12 lags (11 months)

Last updated: 28/06/2023

@author: David Docquier
"""

# Import libraries
import numpy as np
import matplotlib.pyplot as plt

# Options
save_fig = True
nvar = int(8*12)
nlag = 11
lag = np.linspace(0,nlag,12)
conf = 1.96

# Load results PCMCI
beta = np.load('PCMCI/tig5_LIANG_all_PNANAOAOQBOAMOPDOTNAnino34_causal_links_array_tau0-11',allow_pickle=True)
beta = beta[:,:,0:12]
beta = np.abs(beta)

# Scatter plots LKIF
fig = plt.figure(figsize=(24,30))
fig.subplots_adjust(left=0.08,bottom=0.05,right=0.95,top=0.95,wspace=0.2,hspace=0.31)

# Scatter plot of beta as a function of lag - PNA
ax = fig.add_subplot(4,2,1)
#ax.plot(lag,beta[0,1,:],'b--',label='$PNA_{t-l} \longrightarrow NAO_t$')
#ax.plot(lag,beta[0,2,:],'r--',label='$PNA_{t-l} \longrightarrow AO_t$')
#ax.plot(lag,beta[0,3,:],'k--',label='$PNA_{t-l} \longrightarrow QBO_t$')
#ax.plot(lag,beta[0,4,:],'--',color='gray',label='$PNA_{t-l} \longrightarrow AMO_t$')
#ax.plot(lag,beta[0,5,:],'b-',label='$PNA_{t-l} \longrightarrow PDO_t$')
#ax.plot(lag,beta[0,6,:],'r-',label='$PNA_{t-l} \longrightarrow TNA_t$')
ax.plot(lag,beta[0,7,:],'k-',label='$PNA_{t-l} \longrightarrow ENSO_t$')
ax.plot(lag[np.abs(beta[0,1,:])>0],beta[0,1,:][np.abs(beta[0,1,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[0,2,:])>0],beta[0,2,:][np.abs(beta[0,2,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[0,3,:])>0],beta[0,3,:][np.abs(beta[0,3,:])>0],'ko',markersize=15)
ax.plot(lag[np.abs(beta[0,4,:])>0],beta[0,4,:][np.abs(beta[0,4,:])>0],'o',color='gray',markersize=15)
ax.plot(lag[np.abs(beta[0,5,:])>0],beta[0,5,:][np.abs(beta[0,5,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[0,6,:])>0],beta[0,6,:][np.abs(beta[0,6,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[0,7,:])>0],beta[0,7,:][np.abs(beta[0,7,:])>0],'ko',markersize=15)
ax.legend(loc='upper right',fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Path coefficient $|\beta|$',fontsize=24)
ax.grid(linestyle='--')
ax.set_ylim([-0.05,0.5])
ax.set_title('PNA influence',fontsize=28)
ax.set_title('(a)',loc='left',fontsize=28,fontweight='bold')
    
# Scatter plot of beta as a function of lag - NAO
ax = fig.add_subplot(4,2,2)
#ax.plot(lag,beta[1,0,:],'b--',label='$NAO_{t-l} \longrightarrow PNA_t$')
#ax.plot(lag,beta[1,2,:],'r--',label='$NAO_{t-l} \longrightarrow AO_t$')
#ax.plot(lag,beta[1,3,:],'k--',label='$NAO_{t-l} \longrightarrow QBO_t$')
#ax.plot(lag,beta[1,4,:],'--',color='gray',label='$NAO_{t-l} \longrightarrow AMO$')
ax.plot(lag,beta[1,5,:],'b-',label='$NAO_{t-l} \longrightarrow PDO$')
#ax.plot(lag,beta[1,6,:],'r-',label='$NAO_{t-l} \longrightarrow TNA$')
#ax.plot(lag,beta[1,7,:],'k-',label='$NAO_{t-l} \longrightarrow ENSO$')
ax.plot(lag[np.abs(beta[1,0,:])>0],beta[1,0,:][np.abs(beta[1,0,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[1,2,:])>0],beta[1,2,:][np.abs(beta[1,2,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[1,3,:])>0],beta[1,3,:][np.abs(beta[1,3,:])>0],'ko',markersize=15)
ax.plot(lag[np.abs(beta[1,4,:])>0],beta[1,4,:][np.abs(beta[1,4,:])>0],'o',color='gray',markersize=15)
ax.plot(lag[np.abs(beta[1,5,:])>0],beta[1,5,:][np.abs(beta[1,5,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[1,6,:])>0],beta[1,6,:][np.abs(beta[1,6,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[1,7,:])>0],beta[1,7,:][np.abs(beta[1,7,:])>0],'ko',markersize=15)
ax.legend(loc='upper right',fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Path coefficient $|\beta|$',fontsize=24)
ax.grid(linestyle='--')
ax.set_ylim([-0.05,0.5])
ax.set_title('NAO influence',fontsize=28)
ax.set_title('(b)',loc='left',fontsize=28,fontweight='bold')

# Scatter plot of beta as a function of lag - AO
ax = fig.add_subplot(4,2,3)
#ax.plot(lag,beta[2,0,:],'b--',label='$AO_{t-l} \longrightarrow PNA$')
#ax.plot(lag,beta[2,1,:],'r--',label='$AO_{t-l} \longrightarrow NAO$')
ax.plot(lag,beta[2,3,:],'k--',label='$AO_{t-l} \longrightarrow QBO$')
#ax.plot(lag,beta[2,4,:],'--',color='gray',label='$AO_{t-l} \longrightarrow AMO$')
ax.plot(lag,beta[2,5,:],'b-',label='$AO_{t-l} \longrightarrow PDO$')
ax.plot(lag,beta[2,6,:],'r-',label='$AO_{t-l} \longrightarrow TNA$')
#ax.plot(lag,beta[2,7,:],'k-',label='$AO_{t-l} \longrightarrow ENSO$')
ax.plot(lag[np.abs(beta[2,0,:])>0],beta[2,0,:][np.abs(beta[2,0,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[2,1,:])>0],beta[2,1,:][np.abs(beta[2,1,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[2,3,:])>0],beta[2,3,:][np.abs(beta[2,3,:])>0],'ko',markersize=15)
ax.plot(lag[np.abs(beta[2,4,:])>0],beta[2,4,:][np.abs(beta[2,4,:])>0],'o',color='gray',markersize=15)
ax.plot(lag[np.abs(beta[2,5,:])>0],beta[2,5,:][np.abs(beta[2,5,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[2,6,:])>0],beta[2,6,:][np.abs(beta[2,6,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[2,7,:])>0],beta[2,7,:][np.abs(beta[2,7,:])>0],'ko',markersize=15)
ax.legend(loc='upper right',fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Path coefficient $|\beta|$',fontsize=24)
ax.grid(linestyle='--')
ax.set_ylim([-0.05,0.5])
ax.set_title('AO influence',fontsize=28)
ax.set_title('(c)',loc='left',fontsize=28,fontweight='bold')
    
# Scatter plot of beta as a function of lag - QBO
ax = fig.add_subplot(4,2,4)
#ax.plot(lag,beta[3,0,:],'b--',label='$QBO_{t-l} \longrightarrow PNA$')
#ax.plot(lag,beta[3,1,:],'r--',label='$QBO_{t-l} \longrightarrow NAO$')
#ax.plot(lag,beta[3,2,:],'k--',label='$QBO_{t-l} \longrightarrow AO$')
#ax.plot(lag,beta[3,4,:],'--',color='gray',label='$QBO_{t-l} \longrightarrow AMO$')
#ax.plot(lag,beta[3,5,:],'b-',label='$QBO_{t-l} \longrightarrow PDO$')
#ax.plot(lag,beta[3,6,:],'r-',label='$QBO_{t-l} \longrightarrow TNA$')
#ax.plot(lag,beta[3,7,:],'k-',label='$QBO_{t-l} \longrightarrow ENSO$')
ax.plot(lag[np.abs(beta[3,0,:])>0],beta[3,0,:][np.abs(beta[3,0,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[3,1,:])>0],beta[3,1,:][np.abs(beta[3,1,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[3,2,:])>0],beta[3,2,:][np.abs(beta[3,2,:])>0],'ko',markersize=15)
ax.plot(lag[np.abs(beta[3,4,:])>0],beta[3,4,:][np.abs(beta[3,4,:])>0],'o',color='gray',markersize=15)
ax.plot(lag[np.abs(beta[3,5,:])>0],beta[3,5,:][np.abs(beta[3,5,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[3,6,:])>0],beta[3,6,:][np.abs(beta[3,6,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[3,7,:])>0],beta[3,7,:][np.abs(beta[3,7,:])>0],'ko',markersize=15)
ax.legend(loc='upper right',ncol=2,fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Path coefficient $|\beta|$',fontsize=24)
ax.grid(linestyle='--')
ax.axis([-0.5,11.5,-0.05,0.5])
ax.set_title('QBO influence',fontsize=28)
ax.set_title('(d)',loc='left',fontsize=28,fontweight='bold')
    
# Scatter plot of beta as a function of lag - AMO
ax = fig.add_subplot(4,2,5)
#ax.plot(lag,beta[4,0,:],'b--',label='$AMO_{t-l} \longrightarrow PNA$')
#ax.plot(lag,beta[4,1,:],'r--',label='$AMO_{t-l} \longrightarrow NAO$')
ax.plot(lag,beta[4,2,:],'k--',label='$AMO_{t-l} \longrightarrow AO$')
#ax.plot(lag,beta[4,3,:],'--',color='gray',label='$AMO_{t-l} \longrightarrow QBO$')
ax.plot(lag,beta[4,5,:],'b-',label='$AMO_{t-l} \longrightarrow PDO$')
ax.plot(lag,beta[4,6,:],'r-',label='$AMO_{t-l} \longrightarrow TNA$')
#ax.plot(lag,beta[4,7,:],'k-',label='$AMO_{t-l} \longrightarrow ENSO$')
ax.plot(lag[np.abs(beta[4,0,:])>0],beta[4,0,:][np.abs(beta[4,0,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[4,1,:])>0],beta[4,1,:][np.abs(beta[4,1,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[4,2,:])>0],beta[4,2,:][np.abs(beta[4,2,:])>0],'ko',markersize=15)
ax.plot(lag[np.abs(beta[4,3,:])>0],beta[4,3,:][np.abs(beta[4,3,:])>0],'o',color='gray',markersize=15)
ax.plot(lag[np.abs(beta[4,5,:])>0],beta[4,5,:][np.abs(beta[4,5,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[4,6,:])>0],beta[4,6,:][np.abs(beta[4,6,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[4,7,:])>0],beta[4,7,:][np.abs(beta[4,7,:])>0],'ko',markersize=15)
ax.legend(loc='upper right',ncol=2,fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Path coefficient $|\beta|$',fontsize=24)
ax.grid(linestyle='--')
ax.set_ylim([-0.05,0.5])
ax.set_title('AMO influence',fontsize=28)
ax.set_title('(e)',loc='left',fontsize=28,fontweight='bold')

# Scatter plot of beta as a function of lag - PDO
ax = fig.add_subplot(4,2,6)
#ax.plot(lag,beta[5,0,:],'b--',label='$PDO_{t-l} \longrightarrow PNA$')
#ax.plot(lag,beta[5,1,:],'r--',label='$PDO_{t-l} \longrightarrow NAO$')
#ax.plot(lag,beta[5,2,:],'k--',label='$PDO_{t-l} \longrightarrow AO$')
#ax.plot(lag,beta[5,3,:],'--',color='gray',label='$PDO_{t-l} \longrightarrow QBO$')
ax.plot(lag,beta[5,4,:],'b-',label='$PDO_{t-l} \longrightarrow AMO$')
#ax.plot(lag,beta[5,6,:],'r-',label='$PDO_{t-l} \longrightarrow TNA$')
ax.plot(lag,beta[5,7,:],'k-',label='$PDO_{t-l} \longrightarrow ENSO$')
ax.plot(lag[np.abs(beta[5,0,:])>0],beta[5,0,:][np.abs(beta[5,0,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[5,1,:])>0],beta[5,1,:][np.abs(beta[5,1,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[5,2,:])>0],beta[5,2,:][np.abs(beta[5,2,:])>0],'ko',markersize=15)
ax.plot(lag[np.abs(beta[5,3,:])>0],beta[5,3,:][np.abs(beta[5,3,:])>0],'o',color='gray',markersize=15)
ax.plot(lag[np.abs(beta[5,4,:])>0],beta[5,4,:][np.abs(beta[5,4,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[5,6,:])>0],beta[5,6,:][np.abs(beta[5,6,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[5,7,:])>0],beta[5,7,:][np.abs(beta[5,7,:])>0],'ko',markersize=15)
ax.legend(loc='upper right',fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Path coefficient $|\beta|$',fontsize=24)
ax.grid(linestyle='--')
ax.set_ylim([-0.05,0.5])
ax.set_title('PDO influence',fontsize=28)
ax.set_title('(f)',loc='left',fontsize=28,fontweight='bold')

# Scatter plot of beta as a function of lag - TNA
ax = fig.add_subplot(4,2,7)
#ax.plot(lag,beta[6,0,:],'b--',label='$TNA_{t-l} \longrightarrow PNA$')
ax.plot(lag,beta[6,1,:],'r--',label='$TNA_{t-l} \longrightarrow NAO$')
#ax.plot(lag,beta[6,2,:],'k--',label='$TNA_{t-l} \longrightarrow AO$')
ax.plot(lag,beta[6,3,:],'--',color='gray',label='$TNA_{t-l} \longrightarrow QBO$')
ax.plot(lag,beta[6,4,:],'b-',label='$TNA_{t-l} \longrightarrow AMO$')
ax.plot(lag,beta[6,5,:],'r-',label='$TNA_{t-l} \longrightarrow PDO$')
ax.plot(lag,beta[6,7,:],'k-',label='$TNA_{t-l} \longrightarrow ENSO$')
ax.plot(lag[np.abs(beta[6,0,:])>0],beta[6,0,:][np.abs(beta[6,0,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[6,1,:])>0],beta[6,1,:][np.abs(beta[6,1,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[6,2,:])>0],beta[6,2,:][np.abs(beta[6,2,:])>0],'ko',markersize=15)
ax.plot(lag[np.abs(beta[6,3,:])>0],beta[6,3,:][np.abs(beta[6,3,:])>0],'o',color='gray',markersize=15)
ax.plot(lag[np.abs(beta[6,4,:])>0],beta[6,4,:][np.abs(beta[6,4,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[6,5,:])>0],beta[6,5,:][np.abs(beta[6,5,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[6,7,:])>0],beta[6,7,:][np.abs(beta[6,7,:])>0],'ko',markersize=15)
ax.legend(loc='upper right',ncol=2,fontsize=24)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Path coefficient $|\beta|$',fontsize=24)
ax.grid(linestyle='--')
ax.set_ylim([-0.05,0.5])
ax.set_title('TNA influence',fontsize=28)
ax.set_title('(g)',loc='left',fontsize=28,fontweight='bold')

# Scatter plot of beta as a function of lag - ENSO
ax = fig.add_subplot(4,2,8)
ax.plot(lag,beta[7,0,:],'b--',label='$ENSO_{t-l} \longrightarrow PNA$')
#ax.plot(lag,beta[7,1,:],'r--',label='$ENSO_{t-l} \longrightarrow NAO$')
ax.plot(lag,beta[7,2,:],'k--',label='$ENSO_{t-l} \longrightarrow AO$')
ax.plot(lag,beta[7,3,:],'--',color='gray',label='$ENSO_{t-l} \longrightarrow QBO$')
ax.plot(lag,beta[7,4,:],'b-',label='$ENSO_{t-l} \longrightarrow AMO$')
ax.plot(lag,beta[7,5,:],'r-',label='$ENSO_{t-l} \longrightarrow PDO$')
ax.plot(lag,beta[7,6,:],'k-',label='$ENSO_{t-l} \longrightarrow TNA$')
ax.plot(lag[np.abs(beta[7,0,:])>0],beta[7,0,:][np.abs(beta[7,0,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[7,1,:])>0],beta[7,1,:][np.abs(beta[7,1,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[7,2,:])>0],beta[7,2,:][np.abs(beta[7,2,:])>0],'ko',markersize=15)
ax.plot(lag[np.abs(beta[7,3,:])>0],beta[7,3,:][np.abs(beta[7,3,:])>0],'o',color='gray',markersize=15)
ax.plot(lag[np.abs(beta[7,4,:])>0],beta[7,4,:][np.abs(beta[7,4,:])>0],'bo',markersize=15)
ax.plot(lag[np.abs(beta[7,5,:])>0],beta[7,5,:][np.abs(beta[7,5,:])>0],'ro',markersize=15)
ax.plot(lag[np.abs(beta[7,6,:])>0],beta[7,6,:][np.abs(beta[7,6,:])>0],'ko',markersize=15)
ax.legend(loc='upper right',ncol=3,fontsize=20)
ax.tick_params(axis='both',labelsize=20)
ax.set_xlabel('Lag (months)',fontsize=24)
ax.set_ylabel(r'Path coefficient $|\beta|$',fontsize=24)
ax.grid(linestyle='--')
ax.set_ylim([-0.05,0.5])
ax.set_title('ENSO influence',fontsize=28)
ax.set_title('(h)',loc='left',fontsize=28,fontweight='bold')

# Save figure
if save_fig == True:
    fig.savefig('/home/dadocq/Documents/Papers/My_Papers/Causal_Comp/LaTeX/fig10.png')